import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              ZEIR
            </a>
          </div>
        </div>
        <div className={styles.center}>
          爱火箭
        </div>
        <div className={styles.footer}>
          <a className={styles.beiAn} target="_blank" href="https://beian.miit.gov.cn">
            <Image className={styles.beiAnIcon} src={'/icp.png'} alt={'网安备案'} width={14} height={14} style={{}} />
            蜀ICP备20006272号-1
          </a>
          <a className={styles.beiAn} target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=51012402000444" >
            <Image className={styles.beiAnIcon} src={'/wangan.png'} alt={'网安备案'} width={14} height={14} />
            川公网安备 51012402000444号
          </a>
        </div>
      </main>
    </>
  )
}
